services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8081:8081"  # Spring Boot 애플리케이션 컨테이너를 8081로 매핑
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 프로파일 설정
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8082:8080"  # Adminer를 8082로 매핑
    depends_on:
      - mysql

volumes:
  mysql-data: